services:
  db:
    image: mariadb:latest
    hostname: db
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: photo_map
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
